(in-package :sns)

(defun get-motor-state-q (chan)
  (let* ((msg (sns-msg-motor-state-heap-alloc 512))
	 (frame-size (foreign-alloc 'size-t))
	 (r (sns-msg-motor-state-local-get chan msg frame-size (null-pointer) 0)))
    (when (or (eq r :ok)
	      (eq r :missed-frame))
      (let* ((n (foreign-slot-value (foreign-slot-pointer msg '(:struct sns-msg-motor-state) 'header)
				    '(:struct msg-header) 'n))
	     (motor-arr (foreign-alloc :double :count n)))
	(fill-state n (null-pointer) (sns-msg-motor-state-pos msg)
		    (sns-msg-motor-state-incpos msg)
		    motor-arr)
	motor-arr))))
